version: "3.8"

services:
  service-devel:
    build:
      context: .
      dockerfile: ./docker/service.dockerfile
    ports: [5000]
    volumes:
       - .:/src
    command: ["python", "./src/main.py"]
    environment:
      TWITCH_OAUTH: "here"
      TWITCH_CLIENT_ID: "here"
